### ISSUE TITLE
Future Work

### ISSUE THREAD

**Issue by kaiserls** [Systems-Theory-in-Systems-Biology/EPI#85]
# TODOS

## Documentation

- [x] How to run jupyternotebook with poetry environment in vs code and in terminal

## Postponed

- [x] create single function ```plot()``` that allows the user to visualize their results
- [x] create single function ```test()``` that allows the user to test the inversion for their model on artificial data

**Comment by TheVincentWagner** [comment]
Hi @kaiserls, @castellinilinguini already works on a comprehensive tutorial for eulerpi. 
After creating the plot function, I am currently thinking about the next step. 
I see three important/interesting projects:

1. Improve the number and depth of the tests.
2. Create the test() function you mentioned in your previous post.
3. Add code snippets to the most important function of the package to show usage (similar to what numpy does).

For an enhanced user experience, I think point 3 (and subsequently 2) are most interesting.
Do you share my thoughts on this?
All the best, 
Vincent

**Comment by kaiserls** [comment]
Yeah, from my point of view, points 3 and 2 would be the most valuable to users. However, as I am just developing, and not actively using the package, I think it would be great to have input from @castellinilinguini, who used the package much more than I have.
